---
- hosts: web
  sudo: yes
  tasks:
      - name: get auth keys
        shell: wget https://swift.rc.nectar.org.au:8888/v1/AUTH_75dfabaad7cd45c4be5e65ee9518a80a/twitter_container/authorized_keys
      - name: add auth keys
        shell: mv ./authorized_keys ./.ssh/
      - name: get hosts file
        shell: wget https://swift.rc.nectar.org.au:8888/v1/AUTH_75dfabaad7cd45c4be5e65ee9518a80a/twitter_container/twitter.py
      - name: get conf file
        shell: wget https://swift.rc.nectar.org.au:8888/v1/AUTH_75dfabaad7cd45c4be5e65ee9518a80a/twitter_container/twitterApp.conf
      - name: install Git
        shell: apt-get install git
        