---
- hosts: web
  sudo: yes
  tasks:
      - name: get auth keys
        get_url: url=https://swift.rc.nectar.org.au:8888/v1/AUTH_75dfabaad7cd45c4be5e65ee9518a80a/twitter_container/authorized_keys dest=./authorized_keys
      - name: add auth keys
        shell: cp ./authorized_keys ./.ssh/
      - name: get hosts file
        get_url: url=https://swift.rc.nectar.org.au:8888/v1/AUTH_75dfabaad7cd45c4be5e65ee9518a80a/twitter_container/twitter.py dest=./twitter.py
      - name: get conf file
        get_url: url=https://swift.rc.nectar.org.au:8888/v1/AUTH_75dfabaad7cd45c4be5e65ee9518a80a/twitter_container/twitterApp.conf dest=./twitterApp.conf
      - name: get hosts file
        get_url: url=https://swift.rc.nectar.org.au:8888/v1/AUTH_75dfabaad7cd45c4be5e65ee9518a80a/twitter_container/hosts dest=./hosts
      - name: get service file
        get_url: url=https://swift.rc.nectar.org.au:8888/v1/AUTH_75dfabaad7cd45c4be5e65ee9518a80a/twitter_container/harvest-twitter.conf dest=./harvest-twitter.conf
      - name: add service
        shell: cp ./harvest-twitter.conf /etc/init/
      - name: update repository
        apt: update_cache=yes
      - name: install Git
        apt: pkg=git state=latest
      - name: install pip
        apt: pkg=python-pip state=latest update_cache=yes
      - name: pip install tweepy
        pip: name=tweepy
      - name: pip install couchdb
        pip: name=couchdb
      - name: start harvest service
        shell: start harvest-twitter
        